# Lab 01 : Linear module -- solution

# Inspecting a linear module

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Make a linear module  WITHOUT bias that takes input of size 2 and return output of size 3. 

In [2]:
mod=nn.Linear(2,3,bias=False)
print(mod)

Linear(in_features=2, out_features=3, bias=False)


### Print the internal parameters of the module. Try to print the bias and double check that it return you "None"

In [3]:
print(mod.weight)
print(mod.bias)

Parameter containing:
tensor([[-0.5430, -0.3259],
        [-0.5779,  0.5816],
        [-0.6248, -0.3755]], requires_grad=True)
None


### Make a vector $x=\begin{bmatrix}1\\1 \end{bmatrix}$ and feed it to your linear module. What is the output?

In [4]:
x=torch.Tensor([1,1])
print(x)
y=mod(x)
print(y)

tensor([1., 1.])
tensor([-0.8690,  0.0037, -1.0003], grad_fn=<SqueezeBackward3>)


### Change the internal parameters of your module so that the weights become $
W=\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
$. You need to write 6 lines, one per entry to be changed.

In [5]:
mod.weight[0,0]=1
mod.weight[0,1]=2
mod.weight[1,0]=3
mod.weight[1,1]=4
mod.weight[2,0]=5
mod.weight[2,1]=6
print(mod.weight)

Parameter containing:
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], grad_fn=<CopySlices>)


### Feed the vector x to your module with updated parameters. What is the output? 

In [6]:
y=mod(x)
print(y)

tensor([ 3.,  7., 11.], grad_fn=<SqueezeBackward3>)


### Compute by hand $y=Wx$ and check that pytorch got it correctly. 

$$
\begin{bmatrix}
1&2 \\ 3&4 \\ 5&6
\end{bmatrix}
\begin{bmatrix}1\\1 \end{bmatrix}=
\begin{bmatrix}?\\? \\ ? \end{bmatrix}
$$