# Lab 01 : Linear module -- demo

In [ ]:
# For Google Colaboratory
import sys, os
if 'google.colab' in sys.modules:
    from google.colab import drive
    drive.mount('/content/gdrive')
    file_name = 'linear_module_demo.ipynb'
    import subprocess
    path_to_file = subprocess.check_output('find . -type f -name ' + str(file_name), shell=True).decode("utf-8")
    print(path_to_file)
    path_to_file = path_to_file.replace(file_name,"").replace('\n',"")
    os.chdir(path_to_file)
    !pwd

In [1]:
import torch
import torch.nn as nn

### Make a _Linear Module_ that takes input of size 5 and return output of size 3

In [3]:
mod = nn.Linear(5,3)
print(mod)

Linear(in_features=5, out_features=3, bias=True)


### Let's make a random tensor of size 5:

In [4]:
x=torch.rand(5)
print(x)
print(x.size())

tensor([0.5148, 0.6442, 0.5563, 0.4040, 0.9193])
torch.Size([5])


### Feed it to the module:

In [8]:
y=mod(x)
print(y)

tensor([ 0.3300, -0.1137,  0.6271], grad_fn=<ThAddBackward>)


### The output y is computed according to the formula:
$$
\begin{bmatrix}
y_1\\ y_2 \\y_3 
\end{bmatrix} =
\begin{bmatrix}
w_{11} & w_{12} & w_{13}& w_{14}& w_{15} \\
w_{21} & w_{22} & w_{23}& w_{24}& w_{25} \\
w_{31} & w_{32} & w_{33}& w_{34}& w_{35} \\
\end{bmatrix}
\begin{bmatrix}
x_1\\ x_2 \\x_3 \\ x_4 \\x_5
\end{bmatrix}
+
\begin{bmatrix}
b_1\\ b_2 \\b_3 
\end{bmatrix}
$$
### were the $w_{ij}$'s are the weight parameters and the $b_i$'s are the bias parameters. These internal parameters can be access as follow:

In [9]:
print(mod.weight)
print(mod.weight.size())

Parameter containing:
tensor([[ 0.2652, -0.4428,  0.1893,  0.3214, -0.0462],
        [-0.3800,  0.4037,  0.0042,  0.4156, -0.4236],
        [ 0.2434,  0.2813,  0.1570, -0.4028,  0.0869]], requires_grad=True)
torch.Size([3, 5])


In [10]:
print(mod.bias)
print(mod.bias.size())

Parameter containing:
tensor([0.2860, 0.0411, 0.3160], requires_grad=True)
torch.Size([3])


### If we want we can change the internal parameters of the module:

In [11]:
mod.weight[0,0]=0
mod.weight[0,1]=1
mod.weight[0,2]=2
print(mod.weight)

Parameter containing:
tensor([[ 0.0000,  1.0000,  2.0000,  0.3214, -0.0462],
        [-0.3800,  0.4037,  0.0042,  0.4156, -0.4236],
        [ 0.2434,  0.2813,  0.1570, -0.4028,  0.0869]], grad_fn=<CopySlices>)


### We can also make a Linear module without bias:

In [12]:
mod2 = nn.Linear(5,3,bias=False)
print(mod2)

Linear(in_features=5, out_features=3, bias=False)


In [13]:
print(mod2.weight)

Parameter containing:
tensor([[ 0.1703,  0.1601,  0.3649, -0.1387, -0.3961],
        [ 0.4339,  0.2803,  0.0350, -0.3152,  0.3601],
        [-0.0434,  0.4186,  0.1819,  0.0771,  0.1898]], requires_grad=True)


In [14]:
print(mod2.bias)

None
