# Lab 03 : Vanilla neural networks -- demo

# Creating a two-layer network

In [ ]:
# For Google Colaboratory
import sys, os
if 'google.colab' in sys.modules:
    from google.colab import drive
    drive.mount('/content/gdrive')
    file_name = 'vanilla_nn_demo.ipynb'
    import subprocess
    path_to_file = subprocess.check_output('find . -type f -name ' + str(file_name), shell=True).decode("utf-8")
    print(path_to_file)
    path_to_file = path_to_file.replace(file_name,"").replace('\n',"")
    os.chdir(path_to_file)
    !pwd

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### In Pytorch, networks are defined as classes

In [2]:
class two_layer_net(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        super(two_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, hidden_size , bias=True)
        self.layer2 = nn.Linear( hidden_size, output_size , bias=True)        
        
    def forward(self, x):
        
        x = self.layer1(x)
        x = F.relu(x)
        x = self.layer2(x)
        p = F.softmax(x, dim=0)
        
        return p

### Create an instance that takes input of size 2, then transform it into something of size 5, then into something of size 3
$$
\begin{bmatrix}
\times \\ \times 
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times \\ \times \\ \times
\end{bmatrix}
\longrightarrow
\begin{bmatrix}
\times \\ \times \\ \times
\end{bmatrix}
$$

In [3]:
net= two_layer_net(2,5,3)
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### Now we are going to make an input vector and feed it to the network:

In [4]:
x=torch.Tensor([1,1])
print(x)

tensor([1., 1.])


In [5]:
p=net.forward(x)
print(p)

tensor([0.3834, 0.1755, 0.4411], grad_fn=<SoftmaxBackward>)


### Syntactic easy for the forward method

In [6]:
p=net(x)
print(p)

tensor([0.3834, 0.1755, 0.4411], grad_fn=<SoftmaxBackward>)


### Let's check that the probability vector indeed sum to 1:

In [7]:
print( p.sum() )

tensor(1., grad_fn=<SumBackward0>)


### This network is composed of two Linear modules that we have called layer1 and layer2. We can see this when we type:

In [8]:
print(net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### We can access the first module as follow:

In [9]:
print(net.layer1)

Linear(in_features=2, out_features=5, bias=True)


### To get the weights and bias of the first layer we do:

In [10]:
print(net.layer1.weight)

Parameter containing:
tensor([[-0.2154, -0.1284],
        [ 0.6623, -0.0772],
        [ 0.5384, -0.3124],
        [ 0.6685,  0.2045],
        [ 0.1906, -0.6400]], requires_grad=True)


In [11]:
print(net.layer1.bias)

Parameter containing:
tensor([-0.6961,  0.1117, -0.6932,  0.6247, -0.3533], requires_grad=True)


### So to change the first row of the weights from layer 1 you would do:

In [12]:
net.layer1.weight[0,0]=10
net.layer1.weight[0,1]=20

print(net.layer1.weight)

Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.6623, -0.0772],
        [ 0.5384, -0.3124],
        [ 0.6685,  0.2045],
        [ 0.1906, -0.6400]], grad_fn=<CopySlices>)


### Now we are going to feed  $x=\begin{bmatrix}1\\1 \end{bmatrix}$ to this modified network:

In [13]:
p=net(x)
print(p)

tensor([4.2115e-03, 1.1709e-07, 9.9579e-01], grad_fn=<SoftmaxBackward>)


### Alternatively, all the parameters of the network can be accessed by net.parameters(). 

In [14]:
list_of_param = list( net.parameters() )
print(list_of_param)

[Parameter containing:
tensor([[10.0000, 20.0000],
        [ 0.6623, -0.0772],
        [ 0.5384, -0.3124],
        [ 0.6685,  0.2045],
        [ 0.1906, -0.6400]], grad_fn=<CopySlices>), Parameter containing:
tensor([-0.6961,  0.1117, -0.6932,  0.6247, -0.3533], requires_grad=True), Parameter containing:
tensor([[-0.0788, -0.4054,  0.2040,  0.2302, -0.4201],
        [-0.4101, -0.3834, -0.2318, -0.1299, -0.3589],
        [ 0.1029, -0.2742,  0.1420,  0.4409,  0.2585]], requires_grad=True), Parameter containing:
tensor([ 0.0557, -0.2020, -0.2112], requires_grad=True)]
